apiVersion: v1
kind: Service
metadata:
  name: workday-debug
  namespace: flows
spec:
  type: NodePort
  selector:
    stepId: Workday
  ports:
  - protocol: TCP
    port: 9229
    targetPort: 9229
    nodePort: 30000
